plugins = [
"prettier-plugin-astro",
"prettier-plugin-svelte",
]
trailingComma = 'es5'
tabWidth = 2
semi = false
singleQuote = true
quoteProps = 'as-needed'
printWidth = 90
arrowParens = 'avoid'
svelteStrictMode = false
svelteAllowShorthand = true
